### ISSUE TITLE
mqttwarn nine years ago

### ISSUE THREAD

**Issue by amotl** [mqtt-tools/mqttwarn#656]
Dear @jpmens, @sumnerboy12, @juzam, @jfarcher, @gumm, and @fabaff,

as a blast from the past, I am writing to you as founding members and early contributors to mqttwarn, in order to send some big shoutouts to you, and share how mqttwarn looked like nine years ago. Enjoy, and thank you so much for conceiving mqttwarn.

https://github.com/jpmens/mqttwarn/tree/d04f1adef9

Other than this, you may also enjoy the new mqttwarn documentation we have been working on recently, now published at [^1], and its most interesting resource, the venerable notifier catalog [^2].

With kind regards,
Andreas.

[^1]: https://mqttwarn.readthedocs.io/
[^2]: https://mqttwarn.readthedocs.io/en/latest/notifier-catalog.html

**Comment by jpmens** [comment]
Good stuff, Andreas! Thanks for all the work.

**Comment by sumnerboy12** [comment]
Looks great Andreas!

**Comment by amotl** [comment]
Hi again,

first things first: I wish all of you an excellent 2024. This notification was merely thought to credit both of you as parents of mqttwarn, and to make you look at it as kinda proud parents of a now grown-up child. That I contributed my humble share after you carried the toddler through all the teething problems was a great pleasure, but sure enough I didn't want to fish for compliments, yet appreciating them. Maybe we will finally meet when we celebrate mqttwarn becoming a teenager?

Cheers,
Andreas.

NB: As this issue does not have any other value other than praise, it will be closed soon.

**Comment by jpmens** [comment]
Thanks, Andreas, specially for taking the reigns here. Much appreciated!

**Comment by sumnerboy12** [comment]
Yes, thanks Andreas! Without you mqttwarn would still be in nappies I
think...

**Comment by amotl** [comment]
Thanks for your quick responses. Now, enough for the praise, and a happy new year. Closing this ;].
