### ISSUE TITLE
Nightly to latest docker build -  what is the trigger for this?

### ISSUE THREAD

**Issue by psyciknz** [mqtt-tools/mqttwarn#682]
I see the nightly was updated 2 hours ago.   And latest 2 months. 

What's the trigger for latest docker image to be built?   I'm looking at the newly merged environment settings.

**Comment by amotl** [comment]
Hi @psyciknz,

we need to run a new release so that `latest` will point to it. The `nightly` image can be used to consume features before they are released.

Currently, we are working on another iteration, and will run a new release afterwards.

With kind regards,
Andreas.

**Comment by amotl** [comment]
mqttwarn 0.35.0 has been released, so the `latest` OCI images should include the improvement GH-681 by @jhakonen.

**Comment by amotl** [comment]
Hi @psyciknz,

are you already using the latest release, and does it work for you? If so, this issue could be closed?

With kind regards,
Andreas.

**Comment by psyciknz** [comment]
I think I forgot about this. But may as well close.   And I can revisit as needed

**Comment by amotl** [comment]
Thank you. Sorry again for the initial delay. Please let us know about any hiccups you may observe.
